pub mod action_executor;
pub mod action_registry;
pub(crate) mod calculator;
pub mod clipboard_history;
pub mod config;
pub mod contract;
pub mod core_service;
pub mod discovery;
#[cfg(target_os = "windows")]
pub(crate) mod everything_bridge;
#[cfg(target_os = "windows")]
pub(crate) mod file_watcher;
#[cfg(target_os = "windows")]
pub(crate) mod file_watcher_consumer;
pub(crate) mod fts5_search;
pub mod hotkey;
pub mod hotkey_runtime;
pub mod index_store;
pub mod logging;
pub mod model;
pub mod overlay_state;
pub mod plugin_sdk;
pub mod query_dsl;
pub mod runtime;
pub(crate) mod runtime_actions;
pub(crate) mod runtime_commands;
pub(crate) mod runtime_diagnostics;
pub(crate) mod runtime_hotkey;
pub(crate) mod runtime_index;
#[cfg(target_os = "windows")]
pub(crate) mod runtime_loop;
#[cfg(target_os = "windows")]
pub(crate) mod runtime_overlay_rows;
pub(crate) mod runtime_process;
pub(crate) mod runtime_search_session;
pub mod search;
pub(crate) mod search_worker;
pub mod settings;
pub mod startup;
pub(crate) mod tantivy_search;
pub mod transport;
pub mod uninstall_registry;
pub mod updater;
#[cfg(target_os = "windows")]
pub mod windows_overlay;
